"""Ajout de la colonne email et passwd  pour eleve et prof

Revision ID: 795c8036ee9d
Revises: 
Create Date: 2025-03-09 09:11:40.685122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795c8036ee9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))

    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
