"""J'ai implémenté beaucoup de fonctionnalité coté frontend et actuellement je suis la création d'un exercice par un enseignant pour les séances qu'il a crée

Revision ID: b508e17485af
Revises: 
Create Date: 2025-04-06 22:55:54.272227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b508e17485af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('TD', 'TP', 'CM'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercice', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
